services:
  mysql:
    image: mysql:8.0
    container_name: cinemaweb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: cinemaweb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/cinema.sql:/docker-entrypoint-initdb.d/cinema.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p0000" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cinemaweb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
